--insert into HEINO1.ACCOUNT_TYPE (ACCOUNT_TYPE_ID,MNEMONIC,ACCOUNT_TYPE_NAME,CREATION_DATE,MILES_SUM) values (1, 'REWARDS','rewards', '2021-06-12')
--insert into HEINO1.ACCOUNT_TYPE (ACCOUNT_TYPE_ID,MNEMONIC,ACCOUNT_TYPE_NAME,CREATION_DATE,MILES_SUM) values (2, 'MILES','miles', '2021-02-10')
--insert into HEINO1.ACCOUNT_TYPE (ACCOUNT_TYPE_ID,MNEMONIC,ACCOUNT_TYPE_NAME,CREATION_DATE,MILES_SUM) values (3, 'ZAR','zar', '2021-03-06')
insert into HEINO1.ACCOUNT_TYPE (ACCOUNT_TYPE_ID,MNEMONIC,ACCOUNT_TYPE_NAME,CREATION_DATE,MILES_SUM) values ('1', 'PLAY','play', '2021-01-02')



