CREATE SCHEMA HEINO1;

CREATE SEQUENCE ACCOUNT_TYPE_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE ACCOUNT_TYPE
(
    ACCOUNT_TYPE_ID NUMBER(30) NOT NULL,
    MNEMONIC VARCHAR(30) NOT NULL UNIQUE,
    ACCOUNT_TYPE_NAME VARCHAR(30) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    MILES_SUM NUMBER(30) NOT NULL,
    PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE SEQUENCE ACCOUNT_TRANSACTION_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NOCYCLE
    CACHE 20
    NOORDER;

CREATE TABLE ACCOUNT_TRANSACTION
(
    ACCOUNT_TRANS_ID NUMBER(30) NOT NULL,
    ACCOUNT_TYPE_ID NUMBER(30) NOT NULL,
    MEMBER_ID NUMBER(30) NOT NULL,
    AMOUNT NUMBER(30) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    PRIMARY KEY (ACCOUNT_TRANS_ID),
    CONSTRAINT FK_TYPE FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES ACCOUNT_TYPE (ACCOUNT_TYPE_ID)
);